version: '3.3'

services:
  web:
    image: sacred70/lesson26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "25000:25000"
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
  db:
    image: postgres
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME